"""add_fts_ts_vector_to_products

Revision ID: 147af379930e
Revises: e6e865c77859
Create Date: 2026-05-25 21:40:28.588190

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "147af379930e"
down_revision: Union[str, Sequence[str], None] = "e6e865c77859"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "ts_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('english', coalesce(name, '') || ' ' || coalesce(description, ''))",
                persisted=True,
            ),
            nullable=True,
        ),
    )
    op.create_index(
        "idx_products_ts_vector", "products", ["ts_vector"], unique=False, postgresql_using="gin"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_products_ts_vector", table_name="products", postgresql_using="gin")
    op.drop_column("products", "ts_vector")
    # ### end Alembic commands ###
